### ISSUE TITLE
Redirect to website homepage after logout

### ISSUE THREAD

**Issue by gregoriopellegrino** [FusionAuth/wordpress-openid-connect#6]
It would really help the user experience

**Comment by robotdan** [comment]
This WP plugin is a work in progress, but in most case the logout URL is managed by the IdP. 

This means, when you configure your Application in FusionAuth - you will specify a Logout URL. FusionAuth will redirect to this configured URL after a logout. 

https://fusionauth.io/docs/v1/tech/core-concepts/applications#oauth

Hope that helps!
